apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-com-app
  namespace: ovweb
  labels:
    app: hpc-com-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpc-com-app
  template:
    metadata:
      labels:
        app: hpc-com-app
    spec:
      containers:
        - name: hpc-com-app
          image: eldhogeorge86/hpc-com-sample:25050501
          env:
            - name: HP_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
---

